### ISSUE TITLE
mobile

### ISSUE THREAD

**Issue by joeblew99** [lian/gdax-bookmap#1]
i think this is pretty easy to extend so it works on mobiles and desktops with pretty much the same code.

the basic stack is:
1. React native with webview to load in the gl graphs
2. Gomobile compiled service.
 - the golang drawing kit can run here and push the updated images to the react layer over WS.

You might have other ideas. too so just checking

**Comment by lian** [comment]
sadly rendering is a bit to slow, i have tried gopherjs compiles which worked fine but where heavy on the cpu and fans. might revisit at some point.
